# Generated by Django 3.2.15 on 2022-09-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220903_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='user',
            new_name='username',
        ),
    ]
