# Generated by Django 3.2.15 on 2022-09-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='winner',
        ),
    ]
